language: java
os: linux
dist: focal
jdk:
  - openjdk8
  - openjdk11
  - openjdk15
install: skip
before_script: chmod +x gradlew
script: ./gradlew build
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/minecraft/deobfedDeps/providedDummy.jar
  - rm -f  $HOME/.gradle/caches/minecraft/deobfedDeps/compileDummy.jar
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
notifications:
  email: false
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
